### ISSUE TITLE
好像没效果

### ISSUE THREAD

**Issue by superen7527** [Xposed-Modules-Repo/com.hd.hdtool#1]
安卓10和11都不行，手动放位置也不行。没效果啊，伪装版本号这些看得到的没用，那些监听什么的，没地方查看啊。应用域都勾了，玩了一天都不知道在哪看监听结果。路径下文件也没，菜单好像一个都不能用。整个软件像只有ui，不知道是不是我不会用？
看了一下源码还以为监听在日志里，抓了lsp日志结果乱七八糟。。唉。感觉挺好的，第一个能hookandlua应用，不更新了

**Comment by HdShare** [comment]
效果应该是有的
正常来说有权限是
  内部存储/Hd_Tool/应用包名/
如果没权限需要手动移动到
  内部存储/Android/data/应用包名/files/
